-- Comércio / Propostas
-- Persistência, permissões e RLS por organização + empresa.
-- Inclui composição de itens com validação do produto dentro da mesma organização.
-- Esta migração é idempotente para alinhar o repositório ao banco já provisionado.

create table if not exists public.propostas (
  id uuid primary key default gen_random_uuid(),
  organizacao_id uuid not null references public.organizacoes(id) on delete cascade,
  empresa_id uuid not null references public.empresas(id) on delete restrict,
  numero bigint generated by default as identity,
  cliente_id uuid not null references public.parceiros(id) on delete restrict,
  data_emissao date not null default current_date,
  validade date,
  status text not null default 'EM_ELABORACAO' check (status in ('EM_ELABORACAO','ENVIADA','NEGOCIACAO','APROVADA','RECUSADA','CANCELADA')),
  observacoes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint propostas_org_numero_uidx unique (organizacao_id, numero),
  constraint propostas_validade_ck check (validade is null or validade >= data_emissao)
);

create table if not exists public.proposta_itens (
  id uuid primary key default gen_random_uuid(),
  proposta_id uuid not null references public.propostas(id) on delete cascade,
  produto_id uuid not null references public.produtos_servicos(id) on delete restrict,
  quantidade numeric(14,3) not null check (quantidade > 0),
  valor_unitario numeric(14,2) not null check (valor_unitario >= 0),
  desconto numeric(14,2) not null default 0 check (desconto >= 0 and desconto <= quantidade * valor_unitario),
  observacoes text,
  created_at timestamptz not null default now()
);

create index if not exists propostas_empresa_idx on public.propostas(empresa_id);
create index if not exists propostas_cliente_idx on public.propostas(cliente_id);
create index if not exists propostas_status_idx on public.propostas(status);
create index if not exists proposta_itens_proposta_idx on public.proposta_itens(proposta_id);
create index if not exists proposta_itens_produto_idx on public.proposta_itens(produto_id);

insert into public.permissoes (chave, modulo, recurso, acao, descricao, modulo_codigo) values
  ('comercio.propostas.visualizar','COMERCIO','propostas','visualizar','Visualizar propostas comerciais','COMERCIO'),
  ('comercio.propostas.criar','COMERCIO','propostas','criar','Criar propostas comerciais','COMERCIO'),
  ('comercio.propostas.editar','COMERCIO','propostas','editar','Editar propostas comerciais','COMERCIO'),
  ('comercio.propostas.excluir','COMERCIO','propostas','excluir','Excluir propostas comerciais','COMERCIO')
on conflict (chave) do nothing;

alter table public.propostas enable row level security;
alter table public.proposta_itens enable row level security;

drop policy if exists propostas_select on public.propostas;
drop policy if exists propostas_insert on public.propostas;
drop policy if exists propostas_update on public.propostas;
drop policy if exists propostas_delete on public.propostas;

create policy propostas_select on public.propostas for select using (
  app_private.has_permission('comercio.propostas.visualizar')
  and exists (
    select 1 from public.empresas e
    where e.id = propostas.empresa_id and e.organizacao_id = propostas.organizacao_id and e.ativo
      and (
        exists (select 1 from public.perfis p where p.id = (select auth.uid()) and p.is_admin and p.organizacao_id = propostas.organizacao_id)
        or exists (select 1 from public.usuario_empresas ue where ue.usuario_id = (select auth.uid()) and ue.empresa_id = propostas.empresa_id)
      )
  )
);

create policy propostas_insert on public.propostas for insert with check (
  app_private.has_permission('comercio.propostas.criar')
  and exists (
    select 1 from public.empresas e
    where e.id = propostas.empresa_id and e.organizacao_id = propostas.organizacao_id and e.ativo
      and (
        exists (select 1 from public.perfis p where p.id = (select auth.uid()) and p.is_admin and p.organizacao_id = propostas.organizacao_id)
        or exists (select 1 from public.usuario_empresas ue where ue.usuario_id = (select auth.uid()) and ue.empresa_id = propostas.empresa_id)
      )
  )
  and exists (
    select 1 from public.parceiros c
    join public.parceiro_papeis pp on pp.parceiro_id = c.id and pp.papel = 'CLIENTE'
    where c.id = propostas.cliente_id and c.organizacao_id = propostas.organizacao_id and c.ativo
  )
);

create policy propostas_update on public.propostas for update using (
  app_private.has_permission('comercio.propostas.editar')
  and exists (
    select 1 from public.empresas e
    where e.id = propostas.empresa_id and e.organizacao_id = propostas.organizacao_id and e.ativo
      and (
        exists (select 1 from public.perfis p where p.id = (select auth.uid()) and p.is_admin and p.organizacao_id = propostas.organizacao_id)
        or exists (select 1 from public.usuario_empresas ue where ue.usuario_id = (select auth.uid()) and ue.empresa_id = propostas.empresa_id)
      )
  )
) with check (
  app_private.has_permission('comercio.propostas.editar')
  and exists (
    select 1 from public.empresas e
    where e.id = propostas.empresa_id and e.organizacao_id = propostas.organizacao_id and e.ativo
      and (
        exists (select 1 from public.perfis p where p.id = (select auth.uid()) and p.is_admin and p.organizacao_id = propostas.organizacao_id)
        or exists (select 1 from public.usuario_empresas ue where ue.usuario_id = (select auth.uid()) and ue.empresa_id = propostas.empresa_id)
      )
  )
  and exists (
    select 1 from public.parceiros c
    join public.parceiro_papeis pp on pp.parceiro_id = c.id and pp.papel = 'CLIENTE'
    where c.id = propostas.cliente_id and c.organizacao_id = propostas.organizacao_id and c.ativo
  )
);

create policy propostas_delete on public.propostas for delete using (
  app_private.has_permission('comercio.propostas.excluir')
  and exists (
    select 1 from public.empresas e
    where e.id = propostas.empresa_id and e.organizacao_id = propostas.organizacao_id and e.ativo
      and (
        exists (select 1 from public.perfis p where p.id = (select auth.uid()) and p.is_admin and p.organizacao_id = propostas.organizacao_id)
        or exists (select 1 from public.usuario_empresas ue where ue.usuario_id = (select auth.uid()) and ue.empresa_id = propostas.empresa_id)
      )
  )
);

drop policy if exists proposta_itens_select on public.proposta_itens;
drop policy if exists proposta_itens_insert on public.proposta_itens;
drop policy if exists proposta_itens_update on public.proposta_itens;
drop policy if exists proposta_itens_delete on public.proposta_itens;

create policy proposta_itens_select on public.proposta_itens for select using (
  app_private.has_permission('comercio.propostas.visualizar')
  and exists (
    select 1 from public.propostas p
    join public.empresas e on e.id = p.empresa_id and e.organizacao_id = p.organizacao_id and e.ativo
    join public.produtos_servicos ps on ps.id = proposta_itens.produto_id and ps.organizacao_id = p.organizacao_id
    where p.id = proposta_itens.proposta_id
      and (
        exists (select 1 from public.perfis pf where pf.id = (select auth.uid()) and pf.is_admin and pf.organizacao_id = p.organizacao_id)
        or exists (select 1 from public.usuario_empresas ue where ue.usuario_id = (select auth.uid()) and ue.empresa_id = p.empresa_id)
      )
  )
);

create policy proposta_itens_insert on public.proposta_itens for insert with check (
  app_private.has_permission('comercio.propostas.criar')
  and exists (
    select 1 from public.propostas p
    join public.empresas e on e.id = p.empresa_id and e.organizacao_id = p.organizacao_id and e.ativo
    join public.produtos_servicos ps on ps.id = proposta_itens.produto_id and ps.organizacao_id = p.organizacao_id and ps.ativo
    where p.id = proposta_itens.proposta_id
      and (
        exists (select 1 from public.perfis pf where pf.id = (select auth.uid()) and pf.is_admin and pf.organizacao_id = p.organizacao_id)
        or exists (select 1 from public.usuario_empresas ue where ue.usuario_id = (select auth.uid()) and ue.empresa_id = p.empresa_id)
      )
  )
);

create policy proposta_itens_update on public.proposta_itens for update using (
  app_private.has_permission('comercio.propostas.editar')
  and exists (
    select 1 from public.propostas p
    join public.empresas e on e.id = p.empresa_id and e.organizacao_id = p.organizacao_id and e.ativo
    where p.id = proposta_itens.proposta_id
      and (
        exists (select 1 from public.perfis pf where pf.id = (select auth.uid()) and pf.is_admin and pf.organizacao_id = p.organizacao_id)
        or exists (select 1 from public.usuario_empresas ue where ue.usuario_id = (select auth.uid()) and ue.empresa_id = p.empresa_id)
      )
  )
) with check (
  app_private.has_permission('comercio.propostas.editar')
  and exists (
    select 1 from public.propostas p
    join public.empresas e on e.id = p.empresa_id and e.organizacao_id = p.organizacao_id and e.ativo
    join public.produtos_servicos ps on ps.id = proposta_itens.produto_id and ps.organizacao_id = p.organizacao_id and ps.ativo
    where p.id = proposta_itens.proposta_id
      and (
        exists (select 1 from public.perfis pf where pf.id = (select auth.uid()) and pf.is_admin and pf.organizacao_id = p.organizacao_id)
        or exists (select 1 from public.usuario_empresas ue where ue.usuario_id = (select auth.uid()) and ue.empresa_id = p.empresa_id)
      )
  )
);

create policy proposta_itens_delete on public.proposta_itens for delete using (
  (app_private.has_permission('comercio.propostas.excluir') or app_private.has_permission('comercio.propostas.editar'))
  and exists (
    select 1 from public.propostas p
    join public.empresas e on e.id = p.empresa_id and e.organizacao_id = p.organizacao_id and e.ativo
    where p.id = proposta_itens.proposta_id
      and (
        exists (select 1 from public.perfis pf where pf.id = (select auth.uid()) and pf.is_admin and pf.organizacao_id = p.organizacao_id)
        or exists (select 1 from public.usuario_empresas ue where ue.usuario_id = (select auth.uid()) and ue.empresa_id = p.empresa_id)
      )
  )
);
