-- Ordens de Serviço: persistência compartilhada do módulo SERVICOS
create table if not exists public.ordens_servico (
  id uuid primary key default gen_random_uuid(),
  organizacao_id uuid not null references public.organizacoes(id) on delete cascade,
  empresa_id uuid not null references public.empresas(id) on delete restrict,
  numero bigint generated by default as identity,
  cliente_id uuid not null references public.parceiros(id) on delete restrict,
  usina_id uuid references public.usinas(id) on delete restrict,
  tipo text not null,
  descricao text not null,
  prioridade text not null default 'MEDIA' check (prioridade in ('BAIXA','MEDIA','ALTA','URGENTE')),
  status text not null default 'PENDENTE' check (status in ('PENDENTE','AGENDADA','EM_EXECUCAO','CONCLUIDA','CANCELADA')),
  data_abertura date not null default current_date,
  data_agendada date,
  data_conclusao date,
  tecnico_id uuid references public.perfis(id) on delete set null,
  observacoes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ordens_servico_org_numero_uk unique (organizacao_id, numero),
  constraint ordens_servico_datas_ck check (data_conclusao is null or data_conclusao >= data_abertura)
);

create index if not exists ordens_servico_empresa_idx on public.ordens_servico(empresa_id);
create index if not exists ordens_servico_cliente_idx on public.ordens_servico(cliente_id);
create index if not exists ordens_servico_usina_idx on public.ordens_servico(usina_id);
create index if not exists ordens_servico_status_idx on public.ordens_servico(organizacao_id, status);
create index if not exists ordens_servico_tecnico_idx on public.ordens_servico(tecnico_id);

alter table public.ordens_servico enable row level security;

drop policy if exists ordens_servico_select on public.ordens_servico;
drop policy if exists ordens_servico_insert on public.ordens_servico;
drop policy if exists ordens_servico_update on public.ordens_servico;
drop policy if exists ordens_servico_delete on public.ordens_servico;

create policy ordens_servico_select on public.ordens_servico
for select to authenticated
using (
  app_private.has_permission('servicos.ordens_servico.visualizar')
  and exists (
    select 1 from public.empresas e
    where e.id = ordens_servico.empresa_id
      and e.organizacao_id = ordens_servico.organizacao_id
      and e.ativo = true
      and (
        exists (select 1 from public.perfis p where p.id = (select auth.uid()) and p.is_admin = true and p.organizacao_id = ordens_servico.organizacao_id)
        or exists (select 1 from public.usuario_empresas ue where ue.usuario_id = (select auth.uid()) and ue.empresa_id = ordens_servico.empresa_id)
      )
  )
);

create policy ordens_servico_insert on public.ordens_servico
for insert to authenticated
with check (
  app_private.has_permission('servicos.ordens_servico.criar')
  and exists (
    select 1 from public.empresas e
    where e.id = ordens_servico.empresa_id
      and e.organizacao_id = ordens_servico.organizacao_id
      and e.ativo = true
      and (
        exists (select 1 from public.perfis p where p.id = (select auth.uid()) and p.is_admin = true and p.organizacao_id = ordens_servico.organizacao_id)
        or exists (select 1 from public.usuario_empresas ue where ue.usuario_id = (select auth.uid()) and ue.empresa_id = ordens_servico.empresa_id)
      )
  )
  and exists (
    select 1 from public.parceiros c
    join public.parceiro_papeis pp on pp.parceiro_id = c.id and pp.papel = 'CLIENTE'
    where c.id = ordens_servico.cliente_id and c.organizacao_id = ordens_servico.organizacao_id and c.ativo = true
  )
  and (
    ordens_servico.usina_id is null
    or exists (select 1 from public.usinas u where u.id = ordens_servico.usina_id and u.organizacao_id = ordens_servico.organizacao_id and u.empresa_id = ordens_servico.empresa_id)
  )
  and (
    ordens_servico.tecnico_id is null
    or exists (select 1 from public.perfis t where t.id = ordens_servico.tecnico_id and t.organizacao_id = ordens_servico.organizacao_id and t.ativo = true)
  )
);

create policy ordens_servico_update on public.ordens_servico
for update to authenticated
using (
  app_private.has_permission('servicos.ordens_servico.editar')
  and exists (
    select 1 from public.empresas e
    where e.id = ordens_servico.empresa_id
      and e.organizacao_id = ordens_servico.organizacao_id
      and e.ativo = true
      and (
        exists (select 1 from public.perfis p where p.id = (select auth.uid()) and p.is_admin = true and p.organizacao_id = ordens_servico.organizacao_id)
        or exists (select 1 from public.usuario_empresas ue where ue.usuario_id = (select auth.uid()) and ue.empresa_id = ordens_servico.empresa_id)
      )
  )
)
with check (
  app_private.has_permission('servicos.ordens_servico.editar')
  and exists (
    select 1 from public.empresas e
    where e.id = ordens_servico.empresa_id
      and e.organizacao_id = ordens_servico.organizacao_id
      and e.ativo = true
      and (
        exists (select 1 from public.perfis p where p.id = (select auth.uid()) and p.is_admin = true and p.organizacao_id = ordens_servico.organizacao_id)
        or exists (select 1 from public.usuario_empresas ue where ue.usuario_id = (select auth.uid()) and ue.empresa_id = ordens_servico.empresa_id)
      )
  )
  and exists (
    select 1 from public.parceiros c
    join public.parceiro_papeis pp on pp.parceiro_id = c.id and pp.papel = 'CLIENTE'
    where c.id = ordens_servico.cliente_id and c.organizacao_id = ordens_servico.organizacao_id and c.ativo = true
  )
  and (
    ordens_servico.usina_id is null
    or exists (select 1 from public.usinas u where u.id = ordens_servico.usina_id and u.organizacao_id = ordens_servico.organizacao_id and u.empresa_id = ordens_servico.empresa_id)
  )
  and (
    ordens_servico.tecnico_id is null
    or exists (select 1 from public.perfis t where t.id = ordens_servico.tecnico_id and t.organizacao_id = ordens_servico.organizacao_id and t.ativo = true)
  )
);

create policy ordens_servico_delete on public.ordens_servico
for delete to authenticated
using (
  app_private.has_permission('servicos.ordens_servico.excluir')
  and exists (
    select 1 from public.empresas e
    where e.id = ordens_servico.empresa_id
      and e.organizacao_id = ordens_servico.organizacao_id
      and e.ativo = true
      and (
        exists (select 1 from public.perfis p where p.id = (select auth.uid()) and p.is_admin = true and p.organizacao_id = ordens_servico.organizacao_id)
        or exists (select 1 from public.usuario_empresas ue where ue.usuario_id = (select auth.uid()) and ue.empresa_id = ordens_servico.empresa_id)
      )
  )
);

drop trigger if exists trg_ordens_servico_updated_at on public.ordens_servico;
create trigger trg_ordens_servico_updated_at
before update on public.ordens_servico
for each row execute function app_private.set_updated_at();
