create table if not exists public.usinas (
  id uuid primary key default gen_random_uuid(),
  organizacao_id uuid not null references public.organizacoes(id) on delete cascade,
  empresa_id uuid not null references public.empresas(id) on delete restrict,
  cliente_id uuid references public.parceiros(id) on delete restrict,
  codigo bigint generated by default as identity,
  nome text not null,
  endereco text,
  potencia_kwp numeric(14,3),
  quantidade_paineis integer,
  marca_paineis text,
  marca_inversor text,
  numero_serie_inversor text,
  data_instalacao date,
  periodicidade_limpeza_meses integer,
  status text not null default 'IMPLANTACAO' check (status in ('IMPLANTACAO','OPERANDO','INATIVA')),
  observacoes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists usinas_org_codigo_uidx on public.usinas(organizacao_id, codigo);
create index if not exists usinas_org_empresa_idx on public.usinas(empresa_id);
create index if not exists usinas_org_cliente_idx on public.usinas(cliente_id);

alter table public.usinas enable row level security;

drop policy if exists usinas_select on public.usinas;
drop policy if exists usinas_insert on public.usinas;
drop policy if exists usinas_update on public.usinas;
drop policy if exists usinas_delete on public.usinas;

create policy usinas_select on public.usinas for select to authenticated using (
  app_private.has_permission('ufv.usinas.visualizar')
  and exists (
    select 1 from public.empresas e
    where e.id=usinas.empresa_id and e.organizacao_id=usinas.organizacao_id and e.ativo=true
    and (
      exists (select 1 from public.perfis p where p.id=auth.uid() and p.is_admin=true and p.ativo=true and p.organizacao_id=usinas.organizacao_id)
      or exists (select 1 from public.usuario_empresas ue where ue.usuario_id=auth.uid() and ue.empresa_id=usinas.empresa_id)
    )
  )
);

create policy usinas_insert on public.usinas for insert to authenticated with check (
  app_private.has_permission('ufv.usinas.criar')
  and exists (
    select 1 from public.empresas e
    where e.id=usinas.empresa_id and e.organizacao_id=usinas.organizacao_id and e.ativo=true
    and (
      exists (select 1 from public.perfis p where p.id=auth.uid() and p.is_admin=true and p.ativo=true and p.organizacao_id=usinas.organizacao_id)
      or exists (select 1 from public.usuario_empresas ue where ue.usuario_id=auth.uid() and ue.empresa_id=usinas.empresa_id)
    )
  )
  and (usinas.cliente_id is null or exists (
    select 1 from public.parceiros pr where pr.id=usinas.cliente_id and pr.organizacao_id=usinas.organizacao_id and pr.ativo=true
  ))
);

create policy usinas_update on public.usinas for update to authenticated using (
  app_private.has_permission('ufv.usinas.editar')
  and exists (
    select 1 from public.empresas e
    where e.id=usinas.empresa_id and e.organizacao_id=usinas.organizacao_id and e.ativo=true
    and (
      exists (select 1 from public.perfis p where p.id=auth.uid() and p.is_admin=true and p.ativo=true and p.organizacao_id=usinas.organizacao_id)
      or exists (select 1 from public.usuario_empresas ue where ue.usuario_id=auth.uid() and ue.empresa_id=usinas.empresa_id)
    )
  )
) with check (
  app_private.has_permission('ufv.usinas.editar')
  and exists (
    select 1 from public.empresas e
    where e.id=usinas.empresa_id and e.organizacao_id=usinas.organizacao_id and e.ativo=true
    and (
      exists (select 1 from public.perfis p where p.id=auth.uid() and p.is_admin=true and p.ativo=true and p.organizacao_id=usinas.organizacao_id)
      or exists (select 1 from public.usuario_empresas ue where ue.usuario_id=auth.uid() and ue.empresa_id=usinas.empresa_id)
    )
  )
  and (usinas.cliente_id is null or exists (
    select 1 from public.parceiros pr where pr.id=usinas.cliente_id and pr.organizacao_id=usinas.organizacao_id and pr.ativo=true
  ))
);

create policy usinas_delete on public.usinas for delete to authenticated using (
  app_private.has_permission('ufv.usinas.excluir')
  and exists (
    select 1 from public.empresas e
    where e.id=usinas.empresa_id and e.organizacao_id=usinas.organizacao_id
    and (
      exists (select 1 from public.perfis p where p.id=auth.uid() and p.is_admin=true and p.ativo=true and p.organizacao_id=usinas.organizacao_id)
      or exists (select 1 from public.usuario_empresas ue where ue.usuario_id=auth.uid() and ue.empresa_id=usinas.empresa_id)
    )
  )
);

drop trigger if exists trg_usinas_updated_at on public.usinas;
create trigger trg_usinas_updated_at before update on public.usinas
for each row execute function app_private.set_updated_at();

insert into public.permissoes (chave, modulo, recurso, acao, descricao, modulo_codigo)
values
('ufv.usinas.visualizar','UFV','USINAS','visualizar','Consultar usinas','UFV'),
('ufv.usinas.criar','UFV','USINAS','criar','Cadastrar usinas','UFV'),
('ufv.usinas.editar','UFV','USINAS','editar','Alterar usinas','UFV'),
('ufv.usinas.excluir','UFV','USINAS','excluir','Excluir usinas','UFV')
on conflict (chave) do update set modulo=excluded.modulo,recurso=excluded.recurso,acao=excluded.acao,descricao=excluded.descricao,modulo_codigo=excluded.modulo_codigo;