-- Contratos licenciáveis do módulo SERVICOS.
-- Preparado para futura camada de faturamento, sem emissão fiscal nesta etapa.
create table if not exists public.contratos (
  id uuid primary key default gen_random_uuid(),
  organizacao_id uuid not null references public.organizacoes(id) on delete cascade,
  empresa_id uuid not null references public.empresas(id) on delete restrict,
  numero bigint generated by default as identity,
  cliente_id uuid not null references public.parceiros(id) on delete restrict,
  proposta_id uuid references public.propostas(id) on delete restrict,
  ordem_servico_id uuid references public.ordens_servico(id) on delete restrict,
  usina_id uuid references public.usinas(id) on delete restrict,
  titulo text not null,
  descricao text,
  status text not null default 'RASCUNHO' check (status in ('RASCUNHO','EM_NEGOCIACAO','ASSINADO','ATIVO','SUSPENSO','ENCERRADO','CANCELADO')),
  data_emissao date not null default current_date,
  data_assinatura date,
  inicio_vigencia date,
  fim_vigencia date,
  renovacao_automatica boolean not null default false,
  periodicidade_cobranca text check (periodicidade_cobranca is null or periodicidade_cobranca in ('UNICA','MENSAL','BIMESTRAL','TRIMESTRAL','SEMESTRAL','ANUAL')),
  dia_vencimento integer check (dia_vencimento is null or dia_vencimento between 1 and 31),
  valor numeric(14,2) not null default 0 check (valor >= 0),
  observacoes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint contratos_org_numero_uk unique (organizacao_id,numero),
  constraint contratos_datas_ck check ((data_assinatura is null or data_assinatura >= data_emissao) and (fim_vigencia is null or inicio_vigencia is null or fim_vigencia >= inicio_vigencia)),
  constraint contratos_assinado_ck check (status not in ('ASSINADO','ATIVO','SUSPENSO','ENCERRADO') or data_assinatura is not null)
);
create index if not exists contratos_empresa_idx on public.contratos(empresa_id);
create index if not exists contratos_cliente_idx on public.contratos(cliente_id);
create index if not exists contratos_status_idx on public.contratos(organizacao_id,status);
create index if not exists contratos_proposta_idx on public.contratos(proposta_id);
create index if not exists contratos_os_idx on public.contratos(ordem_servico_id);
create index if not exists contratos_usina_idx on public.contratos(usina_id);
alter table public.contratos enable row level security;
insert into public.permissoes(chave,modulo,recurso,acao,descricao,modulo_codigo) values
('servicos.contratos.visualizar','servicos','contratos','visualizar','Visualizar contratos do módulo Serviços','SERVICOS'),
('servicos.contratos.criar','servicos','contratos','criar','Criar contratos do módulo Serviços','SERVICOS'),
('servicos.contratos.editar','servicos','contratos','editar','Editar contratos do módulo Serviços','SERVICOS'),
('servicos.contratos.excluir','servicos','contratos','excluir','Excluir contratos do módulo Serviços','SERVICOS')
on conflict(chave) do update set modulo=excluded.modulo,recurso=excluded.recurso,acao=excluded.acao,descricao=excluded.descricao,modulo_codigo=excluded.modulo_codigo;
drop policy if exists contratos_select on public.contratos;
drop policy if exists contratos_insert on public.contratos;
drop policy if exists contratos_update on public.contratos;
drop policy if exists contratos_delete on public.contratos;
create policy contratos_select on public.contratos for select to authenticated using (
 app_private.has_permission('servicos.contratos.visualizar') and exists(select 1 from public.empresas e where e.id=contratos.empresa_id and e.organizacao_id=contratos.organizacao_id and e.ativo and (exists(select 1 from public.perfis p where p.id=(select auth.uid()) and p.is_admin and p.organizacao_id=contratos.organizacao_id) or exists(select 1 from public.usuario_empresas ue where ue.usuario_id=(select auth.uid()) and ue.empresa_id=contratos.empresa_id)))
);
create policy contratos_insert on public.contratos for insert to authenticated with check (
 app_private.has_permission('servicos.contratos.criar') and
 exists(select 1 from public.empresas e where e.id=contratos.empresa_id and e.organizacao_id=contratos.organizacao_id and e.ativo and (exists(select 1 from public.perfis p where p.id=(select auth.uid()) and p.is_admin and p.organizacao_id=contratos.organizacao_id) or exists(select 1 from public.usuario_empresas ue where ue.usuario_id=(select auth.uid()) and ue.empresa_id=contratos.empresa_id))) and
 exists(select 1 from public.parceiros c join public.parceiro_papeis pp on pp.parceiro_id=c.id and pp.papel='CLIENTE' where c.id=contratos.cliente_id and c.organizacao_id=contratos.organizacao_id and c.ativo) and
 (contratos.proposta_id is null or exists(select 1 from public.propostas p where p.id=contratos.proposta_id and p.organizacao_id=contratos.organizacao_id and p.empresa_id=contratos.empresa_id and p.cliente_id=contratos.cliente_id and p.status='APROVADA')) and
 (contratos.ordem_servico_id is null or exists(select 1 from public.ordens_servico os where os.id=contratos.ordem_servico_id and os.organizacao_id=contratos.organizacao_id and os.empresa_id=contratos.empresa_id and os.cliente_id=contratos.cliente_id)) and
 (contratos.usina_id is null or exists(select 1 from public.usinas u where u.id=contratos.usina_id and u.organizacao_id=contratos.organizacao_id and u.empresa_id=contratos.empresa_id and (u.cliente_id is null or u.cliente_id=contratos.cliente_id)))
);
create policy contratos_update on public.contratos for update to authenticated using (
 app_private.has_permission('servicos.contratos.editar') and exists(select 1 from public.empresas e where e.id=contratos.empresa_id and e.organizacao_id=contratos.organizacao_id and e.ativo and (exists(select 1 from public.perfis p where p.id=(select auth.uid()) and p.is_admin and p.organizacao_id=contratos.organizacao_id) or exists(select 1 from public.usuario_empresas ue where ue.usuario_id=(select auth.uid()) and ue.empresa_id=contratos.empresa_id)))
) with check (
 app_private.has_permission('servicos.contratos.editar') and
 exists(select 1 from public.empresas e where e.id=contratos.empresa_id and e.organizacao_id=contratos.organizacao_id and e.ativo and (exists(select 1 from public.perfis p where p.id=(select auth.uid()) and p.is_admin and p.organizacao_id=contratos.organizacao_id) or exists(select 1 from public.usuario_empresas ue where ue.usuario_id=(select auth.uid()) and ue.empresa_id=contratos.empresa_id))) and
 exists(select 1 from public.parceiros c join public.parceiro_papeis pp on pp.parceiro_id=c.id and pp.papel='CLIENTE' where c.id=contratos.cliente_id and c.organizacao_id=contratos.organizacao_id and c.ativo) and
 (contratos.proposta_id is null or exists(select 1 from public.propostas p where p.id=contratos.proposta_id and p.organizacao_id=contratos.organizacao_id and p.empresa_id=contratos.empresa_id and p.cliente_id=contratos.cliente_id and p.status='APROVADA')) and
 (contratos.ordem_servico_id is null or exists(select 1 from public.ordens_servico os where os.id=contratos.ordem_servico_id and os.organizacao_id=contratos.organizacao_id and os.empresa_id=contratos.empresa_id and os.cliente_id=contratos.cliente_id)) and
 (contratos.usina_id is null or exists(select 1 from public.usinas u where u.id=contratos.usina_id and u.organizacao_id=contratos.organizacao_id and u.empresa_id=contratos.empresa_id and (u.cliente_id is null or u.cliente_id=contratos.cliente_id)))
);
create policy contratos_delete on public.contratos for delete to authenticated using (
 app_private.has_permission('servicos.contratos.excluir') and exists(select 1 from public.empresas e where e.id=contratos.empresa_id and e.organizacao_id=contratos.organizacao_id and e.ativo and (exists(select 1 from public.perfis p where p.id=(select auth.uid()) and p.is_admin and p.organizacao_id=contratos.organizacao_id) or exists(select 1 from public.usuario_empresas ue where ue.usuario_id=(select auth.uid()) and ue.empresa_id=contratos.empresa_id)))
);
drop trigger if exists trg_contratos_updated_at on public.contratos;
create trigger trg_contratos_updated_at before update on public.contratos for each row execute function app_private.set_updated_at();
comment on table public.contratos is 'Contratos licenciáveis do SERVICOS. Preparado para futura camada de faturamento, sem emissão fiscal nesta etapa.';
comment on column public.contratos.status is 'Fluxo contratual; emissão fiscal futura deverá exigir contrato assinado/ativo quando aplicável.';
comment on column public.contratos.proposta_id is 'Origem opcional: somente proposta APROVADA da mesma organização, empresa e cliente.';
comment on column public.contratos.ordem_servico_id is 'Origem opcional: OS da mesma organização, empresa e cliente.';
