-- Faturamento: cobrança, parcelas e recebimentos
-- A emissão fiscal permanece desacoplada e não é realizada por esta migration.

insert into public.modulos_sistema (codigo,nome,descricao,icone,tipo,status,ordem,ativo)
values ('FATURAMENTO','Faturamento','Cobranças, parcelas e recebimentos','Receipt','MODULO','ATIVO',30,true)
on conflict (codigo) do update set nome=excluded.nome,descricao=excluded.descricao,icone=excluded.icone,status='ATIVO',ordem=30,ativo=true,updated_at=now();

insert into public.permissoes (chave,modulo,recurso,acao,descricao,modulo_codigo) values
('faturamento.visualizar','FATURAMENTO','faturamento','visualizar','Visualizar faturamentos e parcelas','FATURAMENTO'),
('faturamento.criar','FATURAMENTO','faturamento','criar','Criar faturamentos e parcelas','FATURAMENTO'),
('faturamento.editar','FATURAMENTO','faturamento','editar','Editar faturamentos e registrar recebimentos','FATURAMENTO'),
('faturamento.excluir','FATURAMENTO','faturamento','excluir','Excluir faturamentos em rascunho','FATURAMENTO')
on conflict (chave) do nothing;

create table if not exists public.faturamentos (
 id uuid primary key default gen_random_uuid(),
 organizacao_id uuid not null references public.organizacoes(id) on delete cascade,
 empresa_id uuid not null references public.empresas(id) on delete restrict,
 numero bigint generated by default as identity,
 cliente_id uuid not null references public.parceiros(id) on delete restrict,
 contrato_id uuid references public.contratos(id) on delete restrict,
 ordem_servico_id uuid references public.ordens_servico(id) on delete restrict,
 proposta_id uuid references public.propostas(id) on delete restrict,
 competencia date not null default current_date,
 emissao date not null default current_date,
 descricao text not null,
 valor_bruto numeric(14,2) not null default 0 check (valor_bruto >= 0),
 desconto numeric(14,2) not null default 0 check (desconto >= 0 and desconto <= valor_bruto),
 acrescimos numeric(14,2) not null default 0 check (acrescimos >= 0),
 valor_total numeric(14,2) generated always as (valor_bruto - desconto + acrescimos) stored,
 status text not null default 'ABERTO' check (status in ('RASCUNHO','ABERTO','PARCIAL','PAGO','CANCELADO')),
 observacoes text,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 constraint faturamentos_org_numero_uidx unique (organizacao_id,numero),
 constraint faturamentos_origem_ck check (contrato_id is not null or ordem_servico_id is not null or proposta_id is not null)
);

create table if not exists public.faturamento_parcelas (
 id uuid primary key default gen_random_uuid(),
 faturamento_id uuid not null references public.faturamentos(id) on delete cascade,
 numero_parcela integer not null check (numero_parcela > 0),
 vencimento date not null,
 valor numeric(14,2) not null check (valor >= 0),
 status text not null default 'ABERTA' check (status in ('ABERTA','PAGA','CANCELADA')),
 data_recebimento date,
 valor_recebido numeric(14,2) not null default 0 check (valor_recebido >= 0 and valor_recebido <= valor),
 forma_recebimento text,
 observacoes text,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 unique(faturamento_id,numero_parcela),
 constraint parcela_recebimento_ck check ((status='PAGA' and data_recebimento is not null and valor_recebido=valor) or (status<>'PAGA' and valor_recebido < valor))
);

create index if not exists faturamentos_empresa_idx on public.faturamentos(empresa_id);
create index if not exists faturamentos_cliente_idx on public.faturamentos(cliente_id);
create index if not exists faturamentos_status_idx on public.faturamentos(status);
create index if not exists faturamentos_competencia_idx on public.faturamentos(organizacao_id,competencia);
create index if not exists faturamento_parcelas_faturamento_idx on public.faturamento_parcelas(faturamento_id);
create index if not exists faturamento_parcelas_vencimento_idx on public.faturamento_parcelas(vencimento,status);

alter table public.faturamentos enable row level security;
alter table public.faturamento_parcelas enable row level security;

drop policy if exists faturamentos_select on public.faturamentos;
drop policy if exists faturamentos_insert on public.faturamentos;
drop policy if exists faturamentos_update on public.faturamentos;
drop policy if exists faturamentos_delete on public.faturamentos;

create policy faturamentos_select on public.faturamentos for select to authenticated using (
 app_private.has_permission('faturamento.visualizar')
 and exists(select 1 from public.empresas e where e.id=faturamentos.empresa_id and e.organizacao_id=faturamentos.organizacao_id and e.ativo and (exists(select 1 from public.perfis p where p.id=(select auth.uid()) and p.is_admin and p.organizacao_id=faturamentos.organizacao_id) or exists(select 1 from public.usuario_empresas ue where ue.usuario_id=(select auth.uid()) and ue.empresa_id=faturamentos.empresa_id)))
);
create policy faturamentos_insert on public.faturamentos for insert to authenticated with check (
 app_private.has_permission('faturamento.criar')
 and exists(select 1 from public.empresas e where e.id=faturamentos.empresa_id and e.organizacao_id=faturamentos.organizacao_id and e.ativo and (exists(select 1 from public.perfis p where p.id=(select auth.uid()) and p.is_admin and p.organizacao_id=faturamentos.organizacao_id) or exists(select 1 from public.usuario_empresas ue where ue.usuario_id=(select auth.uid()) and ue.empresa_id=faturamentos.empresa_id)))
 and exists(select 1 from public.parceiros c join public.parceiro_papeis pp on pp.parceiro_id=c.id and pp.papel='CLIENTE' where c.id=faturamentos.cliente_id and c.organizacao_id=faturamentos.organizacao_id and c.ativo)
 and ((contrato_id is null) or exists(select 1 from public.contratos c where c.id=faturamentos.contrato_id and c.organizacao_id=faturamentos.organizacao_id and c.empresa_id=faturamentos.empresa_id and c.cliente_id=faturamentos.cliente_id and c.status in ('ASSINADO','ATIVO')))
 and ((ordem_servico_id is null) or exists(select 1 from public.ordens_servico o where o.id=faturamentos.ordem_servico_id and o.organizacao_id=faturamentos.organizacao_id and o.empresa_id=faturamentos.empresa_id and o.cliente_id=faturamentos.cliente_id and o.cliente_aprovou=true))
 and ((proposta_id is null) or exists(select 1 from public.propostas p where p.id=faturamentos.proposta_id and p.organizacao_id=faturamentos.organizacao_id and p.empresa_id=faturamentos.empresa_id and p.cliente_id=faturamentos.cliente_id and p.status='APROVADA'))
);
create policy faturamentos_update on public.faturamentos for update to authenticated using (
 app_private.has_permission('faturamento.editar') and exists(select 1 from public.empresas e where e.id=faturamentos.empresa_id and e.organizacao_id=faturamentos.organizacao_id and e.ativo and (exists(select 1 from public.perfis p where p.id=(select auth.uid()) and p.is_admin and p.organizacao_id=faturamentos.organizacao_id) or exists(select 1 from public.usuario_empresas ue where ue.usuario_id=(select auth.uid()) and ue.empresa_id=faturamentos.empresa_id)))
) with check (
 app_private.has_permission('faturamento.editar') and exists(select 1 from public.empresas e where e.id=faturamentos.empresa_id and e.organizacao_id=faturamentos.organizacao_id and e.ativo and (exists(select 1 from public.perfis p where p.id=(select auth.uid()) and p.is_admin and p.organizacao_id=faturamentos.organizacao_id) or exists(select 1 from public.usuario_empresas ue where ue.usuario_id=(select auth.uid()) and ue.empresa_id=faturamentos.empresa_id)))
);
create policy faturamentos_delete on public.faturamentos for delete to authenticated using (
 app_private.has_permission('faturamento.excluir') and status='RASCUNHO' and exists(select 1 from public.empresas e where e.id=faturamentos.empresa_id and e.organizacao_id=faturamentos.organizacao_id and e.ativo and (exists(select 1 from public.perfis p where p.id=(select auth.uid()) and p.is_admin and p.organizacao_id=faturamentos.organizacao_id) or exists(select 1 from public.usuario_empresas ue where ue.usuario_id=(select auth.uid()) and ue.empresa_id=faturamentos.empresa_id)))
);

drop policy if exists faturamento_parcelas_select on public.faturamento_parcelas;
drop policy if exists faturamento_parcelas_insert on public.faturamento_parcelas;
drop policy if exists faturamento_parcelas_update on public.faturamento_parcelas;
drop policy if exists faturamento_parcelas_delete on public.faturamento_parcelas;
create policy faturamento_parcelas_select on public.faturamento_parcelas for select to authenticated using (
 app_private.has_permission('faturamento.visualizar') and exists(select 1 from public.faturamentos f join public.empresas e on e.id=f.empresa_id and e.organizacao_id=f.organizacao_id and e.ativo where f.id=faturamento_parcelas.faturamento_id and (exists(select 1 from public.perfis p where p.id=(select auth.uid()) and p.is_admin and p.organizacao_id=f.organizacao_id) or exists(select 1 from public.usuario_empresas ue where ue.usuario_id=(select auth.uid()) and ue.empresa_id=f.empresa_id)))
);
create policy faturamento_parcelas_insert on public.faturamento_parcelas for insert to authenticated with check (
 app_private.has_permission('faturamento.criar') and exists(select 1 from public.faturamentos f join public.empresas e on e.id=f.empresa_id and e.organizacao_id=f.organizacao_id and e.ativo where f.id=faturamento_parcelas.faturamento_id and f.status='RASCUNHO' and (exists(select 1 from public.perfis p where p.id=(select auth.uid()) and p.is_admin and p.organizacao_id=f.organizacao_id) or exists(select 1 from public.usuario_empresas ue where ue.usuario_id=(select auth.uid()) and ue.empresa_id=f.empresa_id)))
);
create policy faturamento_parcelas_update on public.faturamento_parcelas for update to authenticated using (
 app_private.has_permission('faturamento.editar') and exists(select 1 from public.faturamentos f join public.empresas e on e.id=f.empresa_id and e.organizacao_id=f.organizacao_id and e.ativo where f.id=faturamento_parcelas.faturamento_id and (exists(select 1 from public.perfis p where p.id=(select auth.uid()) and p.is_admin and p.organizacao_id=f.organizacao_id) or exists(select 1 from public.usuario_empresas ue where ue.usuario_id=(select auth.uid()) and ue.empresa_id=f.empresa_id)))
) with check (app_private.has_permission('faturamento.editar'));
create policy faturamento_parcelas_delete on public.faturamento_parcelas for delete to authenticated using (
 app_private.has_permission('faturamento.excluir') and exists(select 1 from public.faturamentos f join public.empresas e on e.id=f.empresa_id and e.organizacao_id=f.organizacao_id and e.ativo where f.id=faturamento_parcelas.faturamento_id and f.status='RASCUNHO' and (exists(select 1 from public.perfis p where p.id=(select auth.uid()) and p.is_admin and p.organizacao_id=f.organizacao_id) or exists(select 1 from public.usuario_empresas ue where ue.usuario_id=(select auth.uid()) and ue.empresa_id=f.empresa_id)))
);

insert into public.organizacao_modulos (organizacao_id,modulo_id,status,observacao)
select o.id,m.id,'ATIVO','Licença full da organização para Faturamento.'
from public.organizacoes o join public.modulos_sistema m on m.codigo='FATURAMENTO'
where o.nome='SOLAR ERP' and o.ativo
on conflict (organizacao_id,modulo_id) do update set status='ATIVO',observacao=excluded.observacao,updated_at=now();
