create extension if not exists pgcrypto;
create schema if not exists app_private;

create table if not exists public.organizacoes (
 id uuid primary key default gen_random_uuid(), nome text not null, nome_fantasia text, documento text,
 ativo boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create unique index if not exists organizacoes_documento_uidx on public.organizacoes(documento) where documento is not null;

create table if not exists public.empresas (
 id uuid primary key default gen_random_uuid(), organizacao_id uuid not null references public.organizacoes(id) on delete cascade,
 codigo text, razao_social text not null, nome_fantasia text, cnpj text,
 tipo text not null default 'MATRIZ' check(tipo in('MATRIZ','FILIAL')),
 empresa_matriz_id uuid references public.empresas(id) on delete restrict, ativo boolean not null default true,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create unique index if not exists empresas_org_codigo_uidx on public.empresas(organizacao_id,codigo) where codigo is not null;

create table if not exists public.perfis (
 id uuid primary key references auth.users(id) on delete cascade, organizacao_id uuid not null references public.organizacoes(id) on delete cascade,
 nome text not null, username text not null, email text, ativo boolean not null default true, is_admin boolean not null default false,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create unique index if not exists perfis_username_uidx on public.perfis(lower(username));
create unique index if not exists perfis_org_email_uidx on public.perfis(organizacao_id,lower(email)) where email is not null;

create table if not exists public.usuario_empresas (
 usuario_id uuid not null references public.perfis(id) on delete cascade,
 empresa_id uuid not null references public.empresas(id) on delete cascade, created_at timestamptz not null default now(),
 primary key(usuario_id,empresa_id)
);

create table if not exists public.grupos_permissao (
 id uuid primary key default gen_random_uuid(), organizacao_id uuid not null references public.organizacoes(id) on delete cascade,
 nome text not null, descricao text, ativo boolean not null default true, created_at timestamptz not null default now(),
 unique(organizacao_id,nome)
);
create table if not exists public.permissoes (
 id uuid primary key default gen_random_uuid(), chave text not null unique, modulo text not null, recurso text not null,
 acao text not null check(acao in('visualizar','criar','editar','excluir','importar','exportar','aprovar')), descricao text
);
create table if not exists public.grupo_permissoes (
 grupo_id uuid not null references public.grupos_permissao(id) on delete cascade,
 permissao_id uuid not null references public.permissoes(id) on delete cascade, primary key(grupo_id,permissao_id)
);
create table if not exists public.usuario_grupos (
 usuario_id uuid not null references public.perfis(id) on delete cascade,
 grupo_id uuid not null references public.grupos_permissao(id) on delete cascade, primary key(usuario_id,grupo_id)
);

create table if not exists public.parceiros (
 id uuid primary key default gen_random_uuid(), organizacao_id uuid not null references public.organizacoes(id) on delete cascade,
 codigo bigint generated by default as identity, tipo_pessoa text not null check(tipo_pessoa in('PF','PJ')),
 nome_razao_social text not null, nome_fantasia text, documento text, inscricao_estadual text, email text,
 telefone text, whatsapp text, ativo boolean not null default true, observacoes text,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create unique index if not exists parceiros_org_documento_uidx on public.parceiros(organizacao_id,documento) where documento is not null;
create table if not exists public.parceiro_papeis (
 parceiro_id uuid not null references public.parceiros(id) on delete cascade,
 papel text not null check(papel in('CLIENTE','FORNECEDOR','FUNCIONARIO','PRESTADOR','OUTRO')), primary key(parceiro_id,papel)
);

create table if not exists public.unidades_medida (
 id uuid primary key default gen_random_uuid(), organizacao_id uuid references public.organizacoes(id) on delete cascade,
 codigo text not null, nome text not null, fator_conversao numeric(18,6), ativo boolean not null default true, unique(organizacao_id,codigo)
);
create table if not exists public.grupos_produto (
 id uuid primary key default gen_random_uuid(), organizacao_id uuid not null references public.organizacoes(id) on delete cascade,
 codigo text, nome text not null, ativo boolean not null default true, unique(organizacao_id,nome)
);
create table if not exists public.familias_produto (
 id uuid primary key default gen_random_uuid(), organizacao_id uuid not null references public.organizacoes(id) on delete cascade,
 grupo_id uuid references public.grupos_produto(id) on delete restrict, codigo text, nome text not null, ativo boolean not null default true,
 unique(organizacao_id,nome)
);
create table if not exists public.produtos_servicos (
 id uuid primary key default gen_random_uuid(), organizacao_id uuid not null references public.organizacoes(id) on delete cascade,
 codigo text, codigo_externo text, nome text not null, descricao text, tipo text not null check(tipo in('PRODUTO','SERVICO')),
 unidade_medida_id uuid references public.unidades_medida(id) on delete restrict,
 grupo_id uuid references public.grupos_produto(id) on delete restrict, familia_id uuid references public.familias_produto(id) on delete restrict,
 tipo_consumo text, controla_estoque boolean not null default false, controla_serial boolean not null default false, ativo boolean not null default true,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create unique index if not exists produtos_org_codigo_uidx on public.produtos_servicos(organizacao_id,codigo) where codigo is not null;
create table if not exists public.produto_empresas (
 produto_id uuid not null references public.produtos_servicos(id) on delete cascade,
 empresa_id uuid not null references public.empresas(id) on delete cascade, ativo boolean not null default true, primary key(produto_id,empresa_id)
);

create table if not exists public.configuracoes_sistema (
 id uuid primary key default gen_random_uuid(), organizacao_id uuid not null references public.organizacoes(id) on delete cascade,
 chave text not null, valor jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 unique(organizacao_id,chave)
);
create table if not exists public.auditoria_eventos (
 id bigint generated always as identity primary key, organizacao_id uuid references public.organizacoes(id) on delete set null,
 usuario_id uuid references auth.users(id) on delete set null, modulo text, entidade text, entidade_id uuid, acao text not null,
 dados_anteriores jsonb, dados_novos jsonb, created_at timestamptz not null default now()
);

create or replace function app_private.user_org_ids() returns setof uuid language sql stable security definer set search_path=public,app_private as $$
 select organizacao_id from public.perfis where id=auth.uid() and ativo=true;
$$;
create or replace function app_private.has_org_access(p_org uuid) returns boolean language sql stable security definer set search_path=public,app_private as $$
 select exists(select 1 from public.perfis where id=auth.uid() and ativo=true and organizacao_id=p_org);
$$;
grant usage on schema app_private to authenticated;

do $$
declare t text;
begin
 foreach t in array array['organizacoes','empresas','perfis','usuario_empresas','grupos_permissao','permissoes','grupo_permissoes','usuario_grupos','parceiros','parceiro_papeis','unidades_medida','grupos_produto','familias_produto','produtos_servicos','produto_empresas','configuracoes_sistema','auditoria_eventos'] loop
  execute format('alter table public.%I enable row level security',t);
 end loop;
end $$;

drop policy if exists organizacoes_select on public.organizacoes;
create policy organizacoes_select on public.organizacoes for select to authenticated using(app_private.has_org_access(id));

do $$
declare t text;
begin
 foreach t in array array['empresas','grupos_permissao','parceiros','grupos_produto','familias_produto','produtos_servicos','configuracoes_sistema'] loop
  execute format('drop policy if exists %I on public.%I',t||'_org_access',t);
  execute format('create policy %I on public.%I for all to authenticated using(app_private.has_org_access(organizacao_id)) with check(app_private.has_org_access(organizacao_id))',t||'_org_access',t);
 end loop;
end $$;

drop policy if exists perfis_self_or_org on public.perfis;
create policy perfis_self_or_org on public.perfis for select to authenticated using(id=auth.uid() or app_private.has_org_access(organizacao_id));

drop policy if exists usuario_empresas_org_access on public.usuario_empresas;
create policy usuario_empresas_org_access on public.usuario_empresas for all to authenticated
using(exists(select 1 from public.empresas e where e.id=empresa_id and app_private.has_org_access(e.organizacao_id)))
with check(exists(select 1 from public.empresas e where e.id=empresa_id and app_private.has_org_access(e.organizacao_id)));

drop policy if exists permissoes_authenticated on public.permissoes;
create policy permissoes_authenticated on public.permissoes for select to authenticated using(true);

drop policy if exists grupo_permissoes_org_access on public.grupo_permissoes;
create policy grupo_permissoes_org_access on public.grupo_permissoes for all to authenticated
using(exists(select 1 from public.grupos_permissao g where g.id=grupo_id and app_private.has_org_access(g.organizacao_id)))
with check(exists(select 1 from public.grupos_permissao g where g.id=grupo_id and app_private.has_org_access(g.organizacao_id)));

drop policy if exists usuario_grupos_org_access on public.usuario_grupos;
create policy usuario_grupos_org_access on public.usuario_grupos for all to authenticated
using(exists(select 1 from public.grupos_permissao g where g.id=grupo_id and app_private.has_org_access(g.organizacao_id)))
with check(exists(select 1 from public.grupos_permissao g where g.id=grupo_id and app_private.has_org_access(g.organizacao_id)));

drop policy if exists parceiro_papeis_org_access on public.parceiro_papeis;
create policy parceiro_papeis_org_access on public.parceiro_papeis for all to authenticated
using(exists(select 1 from public.parceiros p where p.id=parceiro_id and app_private.has_org_access(p.organizacao_id)))
with check(exists(select 1 from public.parceiros p where p.id=parceiro_id and app_private.has_org_access(p.organizacao_id)));

drop policy if exists unidades_medida_access on public.unidades_medida;
create policy unidades_medida_access on public.unidades_medida for all to authenticated
using(organizacao_id is null or app_private.has_org_access(organizacao_id))
with check(organizacao_id is null or app_private.has_org_access(organizacao_id));

drop policy if exists produto_empresas_org_access on public.produto_empresas;
create policy produto_empresas_org_access on public.produto_empresas for all to authenticated
using(exists(select 1 from public.produtos_servicos p where p.id=produto_id and app_private.has_org_access(p.organizacao_id)))
with check(exists(select 1 from public.produtos_servicos p where p.id=produto_id and app_private.has_org_access(p.organizacao_id)));

drop policy if exists auditoria_eventos_org_access on public.auditoria_eventos;
create policy auditoria_eventos_org_access on public.auditoria_eventos for select to authenticated using(organizacao_id is null or app_private.has_org_access(organizacao_id));

insert into public.permissoes(chave,modulo,recurso,acao,descricao) values
('core.usuarios.visualizar','CORE','USUARIOS','visualizar','Consultar usuários'),
('core.usuarios.criar','CORE','USUARIOS','criar','Cadastrar usuários'),
('core.usuarios.editar','CORE','USUARIOS','editar','Alterar usuários'),
('core.usuarios.excluir','CORE','USUARIOS','excluir','Desativar usuários'),
('core.parceiros.visualizar','CORE','PARCEIROS','visualizar','Consultar parceiros'),
('core.parceiros.criar','CORE','PARCEIROS','criar','Cadastrar parceiros'),
('core.parceiros.editar','CORE','PARCEIROS','editar','Alterar parceiros'),
('core.parceiros.excluir','CORE','PARCEIROS','excluir','Excluir/desativar parceiros'),
('core.produtos.visualizar','CORE','PRODUTOS','visualizar','Consultar produtos e serviços'),
('core.produtos.criar','CORE','PRODUTOS','criar','Cadastrar produtos e serviços'),
('core.produtos.editar','CORE','PRODUTOS','editar','Alterar produtos e serviços'),
('core.produtos.excluir','CORE','PRODUTOS','excluir','Desativar produtos e serviços'),
('core.configuracoes.editar','CORE','CONFIGURACOES','editar','Alterar configurações do ERP')
on conflict(chave) do nothing;

create or replace function app_private.set_updated_at() returns trigger language plpgsql as $$
begin new.updated_at=now(); return new; end; $$;
do $$
declare t text;
begin
 foreach t in array array['organizacoes','empresas','perfis','parceiros','produtos_servicos','configuracoes_sistema'] loop
  execute format('drop trigger if exists %I on public.%I','trg_'||t||'_updated_at',t);
  execute format('create trigger %I before update on public.%I for each row execute function app_private.set_updated_at()','trg_'||t||'_updated_at',t);
 end loop;
end $$;
